import { Lesson } from './types';

export const LESSONS: Lesson[] = [
  // Foundation
  {
    id: 'intro',
    title: 'What is UI/UX',
    description: 'The basics of design.',
    icon: 'BookOpen',
    category: 'Foundation',
  },
  {
    id: 'psychology',
    title: 'UX Psychology',
    description: 'How users think and behave.',
    icon: 'Brain',
    category: 'Foundation',
  },
  {
    id: 'research',
    title: 'User Research',
    description: 'Understanding your users.',
    icon: 'Search',
    category: 'Foundation',
  },
  {
    id: 'personas',
    title: 'Personas & User Journeys',
    description: 'Mapping the user experience.',
    icon: 'Users',
    category: 'Foundation',
  },
  {
    id: 'ia',
    title: 'Information Architecture',
    description: 'Organizing content effectively.',
    icon: 'Network',
    category: 'Foundation',
  },
  {
    id: 'flows',
    title: 'User Flows',
    description: 'Pathways to conversion.',
    icon: 'GitMerge',
    category: 'Foundation',
  },

  // UI Design Principles
  {
    id: 'color',
    title: 'Color & Contrast',
    description: 'Accessibility and emotion.',
    icon: 'Palette',
    category: 'UI Design Principles',
  },
  {
    id: 'typography',
    title: 'Typography',
    description: 'Readability and hierarchy.',
    icon: 'Type',
    category: 'UI Design Principles',
  },
  {
    id: 'spacing',
    title: 'Spacing & Layout',
    description: 'Whitespace and grouping.',
    icon: 'Layout',
    category: 'UI Design Principles',
  },
  {
    id: 'hierarchy',
    title: 'Visual Hierarchy',
    description: 'Guiding the user eye.',
    icon: 'Layers',
    category: 'UI Design Principles',
  },
  {
    id: 'responsive',
    title: 'Responsive Design',
    description: 'Designing for all screens.',
    icon: 'Smartphone',
    category: 'UI Design Principles',
  },
  {
    id: 'design_styles',
    title: 'Modern UI Styles',
    description: 'Neumorphism, Glassmorphism & more.',
    icon: 'Palette',
    category: 'UI Design Principles',
  },

  // UI Components
  {
    id: 'navigation',
    title: 'Navigation',
    description: 'Progressive disclosure.',
    icon: 'Compass',
    category: 'UI Components',
  },
  {
    id: 'cards',
    title: 'Cards & Grids',
    description: 'Content organization.',
    icon: 'LayoutGrid',
    category: 'UI Components',
  },
  {
    id: 'forms',
    title: 'Forms & Inputs',
    description: 'Data entry and validation.',
    icon: 'FileText',
    category: 'UI Components',
  },
  {
    id: 'overlays',
    title: 'Drawers, Modals & Sidebars',
    description: 'Context & interruptions.',
    icon: 'AppWindow',
    category: 'UI Components',
  },
  {
    id: 'tooltips',
    title: 'Tooltips & Popovers',
    description: 'Contextual help.',
    icon: 'HelpCircle',
    category: 'UI Components',
  },
  {
    id: 'feedback',
    title: 'Feedback & Status',
    description: 'Toasts, banners & alerts.',
    icon: 'Bell',
    category: 'UI Components',
  },
  {
    id: 'progress',
    title: 'Progress & Loading',
    description: 'Skeletons and spinners.',
    icon: 'Hourglass',
    category: 'UI Components',
  },
  {
    id: 'tabs',
    title: 'Tabs',
    description: 'Parallel content views.',
    icon: 'Layout',
    category: 'UI Components',
  },
  {
    id: 'carousel',
    title: 'Carousels',
    description: 'Sliding content blocks.',
    icon: 'GalleryHorizontal',
    category: 'UI Components',
  },
  {
    id: 'bento_grid',
    title: 'Bento Grids',
    description: 'Modern hierarchical layouts.',
    icon: 'Grid',
    category: 'UI Components',
  },
  {
    id: 'accordion',
    title: 'Accordion',
    description: 'Collapsible content sections.',
    icon: 'List',
    category: 'UI Components',
  },
  {
    id: 'breadcrumbs',
    title: 'Breadcrumbs',
    description: 'Hierarchical navigation trails.',
    icon: 'ChevronRight',
    category: 'UI Components',
  },
  {
    id: 'radio_buttons',
    title: 'Radio Buttons',
    description: 'Mutually exclusive selections.',
    icon: 'Circle',
    category: 'UI Components',
  },
  {
    id: 'toast',
    title: 'Toast',
    description: 'Brief, non-disruptive feedback.',
    icon: 'Bell',
    category: 'UI Components',
  },
  {
    id: 'snackbar',
    title: 'Snackbar',
    description: 'Brief, actionable feedback.',
    icon: 'CheckCircle2',
    category: 'UI Components',
  },

  // Interaction Design
  {
    id: 'states',
    title: 'Interactive States',
    description: 'Hover, focus & feedback.',
    icon: 'MousePointerClick',
    category: 'Interaction Design',
  },
  {
    id: 'microinteractions',
    title: 'Micro-Interactions',
    description: 'Delightful details.',
    icon: 'Zap',
    category: 'Interaction Design',
  },
  {
    id: 'animations',
    title: 'Animations',
    description: 'Motion and transitions.',
    icon: 'PlayCircle',
    category: 'Interaction Design',
  },

  // Product UX
  {
    id: 'onboarding',
    title: 'Onboarding UX',
    description: 'Welcoming new users.',
    icon: 'Rocket',
    category: 'Product UX',
  },
  {
    id: 'empty_states',
    title: 'Empty States & Edge Cases',
    description: 'Designing for nothing.',
    icon: 'Ghost',
    category: 'Product UX',
  },
  {
    id: 'accessibility',
    title: 'Accessibility',
    description: 'Designing for everyone.',
    icon: 'Eye',
    category: 'Product UX',
  },
  {
    id: 'testing',
    title: 'Usability Testing',
    description: 'Validating your designs.',
    icon: 'CheckCircle',
    category: 'Product UX',
  },
  {
    id: 'metrics',
    title: 'UX Metrics',
    description: 'Measuring success.',
    icon: 'BarChart',
    category: 'Product UX',
  },

  // Advanced
  {
    id: 'systems',
    title: 'Design Systems',
    description: 'Scaling your design.',
    icon: 'Component',
    category: 'Advanced',
  },
  {
    id: 'dataviz',
    title: 'Data Visualization',
    description: 'Charts, graphs & density.',
    icon: 'PieChart',
    category: 'Advanced',
  },
  {
    id: 'search_filter',
    title: 'Search & Filtering',
    description: 'Faceted search & patterns.',
    icon: 'Search',
    category: 'Advanced',
  },
  {
    id: 'data_handling',
    title: 'Complex Data',
    description: 'Tables, pagination & scroll.',
    icon: 'Table',
    category: 'Advanced',
  },
  {
    id: 'guided_processes',
    title: 'Guided Processes',
    description: 'Steppers, wizards & tours.',
    icon: 'ListChecks',
    category: 'Advanced',
  },
  {
    id: 'performance_ux',
    title: 'Performance UX',
    description: 'Skeletons & perceived speed.',
    icon: 'Zap',
    category: 'Advanced',
  },
  {
    id: 'mobile_ux',
    title: 'Mobile Interactions',
    description: 'Gestures & thumb zones.',
    icon: 'Smartphone',
    category: 'Advanced',
  },
  {
    id: 'theming',
    title: 'Theming & Personalization',
    description: 'Dark mode & preferences.',
    icon: 'SunMoon',
    category: 'Advanced',
  },

  // Emerging Tech & Modern Paradigms
  {
    id: 'ai_ux',
    title: 'AI & Conversational UX',
    description: 'Designing for LLMs & Chatbots.',
    icon: 'Bot',
    category: 'Emerging Tech & Modern Paradigms',
  },
  {
    id: 'spatial_design',
    title: 'Spatial Design (AR/VR)',
    description: '3D interfaces & depth.',
    icon: 'Box',
    category: 'Emerging Tech & Modern Paradigms',
  },
  {
    id: 'voice_ui',
    title: 'Voice User Interfaces',
    description: 'Voice commands & feedback.',
    icon: 'Mic',
    category: 'Emerging Tech & Modern Paradigms',
  },

  // Ethics, Trust & Global Reach
  {
    id: 'ethical_design',
    title: 'Ethical Design & Dark Patterns',
    description: 'Building user trust.',
    icon: 'ShieldAlert',
    category: 'Ethics, Trust & Global Reach',
  },
  {
    id: 'privacy_security',
    title: 'Data Privacy & Security UX',
    description: 'Consent & permissions.',
    icon: 'Lock',
    category: 'Ethics, Trust & Global Reach',
  },
  {
    id: 'localization',
    title: 'Localization & i18n',
    description: 'Designing for a global audience.',
    icon: 'Globe',
    category: 'Ethics, Trust & Global Reach',
  },

  // Engagement & Retention
  {
    id: 'gamification',
    title: 'Gamification & Rewards',
    description: 'Motivating users through game mechanics.',
    icon: 'Trophy',
    category: 'Engagement & Retention',
  },
  {
    id: 'habit_loops',
    title: 'Habit Loops & Hooks',
    description: 'Building habit-forming products.',
    icon: 'Repeat',
    category: 'Engagement & Retention',
  },
  {
    id: 'push_notifications',
    title: 'Push Notifications UX',
    description: 'Engaging without annoying.',
    icon: 'BellRing',
    category: 'Engagement & Retention',
  },

  // Final Review
  {
    id: 'annotated_mockup',
    title: 'UI Anatomy Mockup',
    description: 'Full-page annotated UI components.',
    icon: 'ScanSearch',
    category: 'Final Review',
  },
];
